version: '3'
services:
  app:
    build: .
    container_name: driv1_backend
    # comment this for test
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    env_file:
      - dev.env
    command: bash -c "PYTHONPATH=/app python3 app/main.py"
